columns:
  longitude: float
  latitude: float
  housing_median_age: float
  total_rooms: float
  total_bedrooms: float
  population: float
  median_income: float
  median_house_value: float
  ocean_proximity: category


target_column: median_house_value


domain_value:
  ocean_proximity:
    - <H OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN